export enum UserRole {
  CITIZEN = 'CITIZEN',
  AGENT = 'AGENT',
  ADMIN = 'ADMIN',
}

export enum AgentVerificationStatus {
  PENDING = 'PENDING',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum RequestStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  ASSIGNED = 'ASSIGNED',
  PICKED_UP = 'PICKED_UP',
  IN_TRANSIT_TO_AUTHORITY = 'IN_TRANSIT_TO_AUTHORITY',
  AT_AUTHORITY = 'AT_AUTHORITY',
  AUTHENTICATED = 'AUTHENTICATED',
  REJECTED_BY_AUTHORITY = 'REJECTED_BY_AUTHORITY',
  IN_TRANSIT_TO_CITIZEN = 'IN_TRANSIT_TO_CITIZEN',
  DELIVERED = 'DELIVERED',
  CLOSED = 'CLOSED',
  ON_HOLD = 'ON_HOLD',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
}

export enum PaymentMethod {
  CARD = 'CARD',
  MOBILE_WALLET = 'MOBILE_WALLET',
  FAWRY_CODE = 'FAWRY_CODE',
  MEEZA = 'MEEZA',
  PAYPAL = 'PAYPAL',
}

export enum PaymentGateway {
  MOCK = 'MOCK',
  PAYMOB = 'PAYMOB',
  FAWRY = 'FAWRY',
  PAYPAL = 'PAYPAL',
}

export enum DocumentUploadType {
  ORIGINAL_DOCUMENT = 'ORIGINAL_DOCUMENT',
  SUPPORTING_DOCUMENT = 'SUPPORTING_DOCUMENT',
  PROOF_OF_CUSTODY = 'PROOF_OF_CUSTODY',
  AUTHORITY_RESULT = 'AUTHORITY_RESULT',
  DELIVERY_PROOF = 'DELIVERY_PROOF',
  AGENT_VERIFICATION = 'AGENT_VERIFICATION',
  IDENTITY_DOCUMENT = 'IDENTITY_DOCUMENT',
}

export enum NotificationType {
  STATUS_UPDATE = 'STATUS_UPDATE',
  PAYMENT = 'PAYMENT',
  ASSIGNMENT = 'ASSIGNMENT',
  SYSTEM = 'SYSTEM',
}

export enum AuthorityType {
  EMBASSY = 'EMBASSY',
  MINISTRY = 'MINISTRY',
  NOTARY = 'NOTARY',
  OTHER = 'OTHER',
}

export enum ShippingProvider {
  IN_HOUSE_AGENT = 'IN_HOUSE_AGENT',
  BOSTA = 'BOSTA',
  ARAMEX = 'ARAMEX',
}
